### ISSUE TITLE
Material conversion for landscape scene could be improved

### ISSUE THREAD

**Issue by mmp** [mmp/pbrt-v4-scenes#1]
Some of the plant colors aren't great. This green is particularly off:

![Screenshot from 2020-08-18 13-50-29](https://user-images.githubusercontent.com/102567/90564271-f52e1b80-e159-11ea-9736-6425d5f20fab.png)

**Comment by vilya** [comment]
This might be related: in the landscape scene there are 268 MakeNamedMaterial directives but 0 NamedMaterial directives, so none of the named materials are never actually used.

**Comment by vilya** [comment]
In the PBRTv3 version of the scene, there are the same number of MakeNamedMaterial directives and they all seem to be used as parameters to mix materials. There don't seem to be any mix materials in the PBRTv4 scene. Maybe `pbrt --upgrade` missed them out?

**Comment by mmp** [comment]
Good clue, though that turns out to actually be a red herring. (Basically, pbrt-v3's BSDF models were very much of the "add a bunch of lobes together until it looks good" form, while v4 tries to be a bit more principled; those are leftovers from the automated conversion of the scene.)

That said, this inspired me to spend more time on the scene, improving both the lighting and material conversion. It's a lot better now and matches the v3 version of the scene pretty well.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/102567/198608195-9160ee57-d636-4f4c-b01c-01072344bac0.png">
