### ISSUE TITLE
Empty Object Groups

### ISSUE THREAD

**Issue by Xaldew** [mmp/pbrt-v4-scenes#15]
Hello,

I happened to be working a little bit on the Landscape scene, and noticed that there seems to be a few empty Object groups/instances:

```
AttributeBegin
    ObjectBegin "Brennnessel Instance.4"
    ObjectEnd
AttributeEnd
```

```
AttributeBegin
    ObjectBegin "xref_Picea_5mt.c4d Instance"
    ObjectEnd
AttributeEnd
```

Is there perhaps some missing geometry here, or am I misunderstanding how the (empty) `ObjectBegin` statement works?

**Comment by mmp** [comment]
Interesting! Those should be no-ops, with no effect on the scene that is rendered. I assume that they are an artifact of the automated scripts used to export the original scene to pbrt's format.

**Comment by Xaldew** [comment]
Good to know, thanks! I also found some more oddities, such as many empty `AttributeBegin` blocks and `MakeNamedMaterial` without a corresponding `NamedMaterial` (but with an "anonymous" `Material` instead), do you want me to report similar things I come across or is that really just a bit of noise?

**Comment by mmp** [comment]
No need to report that sort of thing unless there's some evidence that it's affecting rendering (though that would likely indicate a pbrt bug in any case...)
