### ISSUE TITLE
Disney cloud scene and dataset

### ISSUE THREAD

**Issue by webanck** [mmp/pbrt-v4-scenes#3]
I adapted the Mitsuba scene file of [the cloud dataset provided by Disney](https://disney-animation.s3.amazonaws.com/uploads/production/data_set_asset/1/asset/Cloud_Readme.pdf) to the new pbrt-v4 file description format, and converted the OpenVDB file representing the cloud's density to a NanoVDB file.

The content is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License and the file size is about 4Go at full resolution, 90Mo at "quarter" resolution.
Do you think it could be incorporated it in the pbrt-v4-scenes, and would you like me to do so ?

Here is the scene with the quarter resolution cloud rendered using pbrt-v4 with 256 samples per pixel.
![disneyCloud-pbrt-v4-256spp](https://user-images.githubusercontent.com/6747237/93363671-dbaaed00-f847-11ea-88b7-065a30243329.png)

**Comment by mmp** [comment]
Cool! It would be great to have that as part of the pbrt-v4-scenes, and if you can send a PR, that'd be great.

Agreed that it should be fine, given the license (so long as the license is mentioned and linked to from the pbrt-v4-scenes README.md, I think..)

github doesn't allow files larger than 100MB, so it'd have to be the quarter resolution one...
