### ISSUE TITLE
Tint parameter in Bistro materials

### ISSUE THREAD

**Issue by renderdude** [mmp/pbrt-v4-scenes#5]
PBRT commit 44eaab0 (6/26) removed "tint" as a parameter from "dielectric". The bistro materials (materials.pbrt, line 731) is still using "tint", and hence the renderer fails with an unused parameter error.

**Comment by mmp** [comment]
Thanks for reporting this!

**Comment by mmp** [comment]
Fixed in 68399f30d5777de17b545f69d6204268b69427e7, which incorrectly claims that it fixes #2, but anyway...
