### ISSUE TITLE
CUDA error: out of memory..while trying hair/hair-actual-bsdf.pbrt

### ISSUE THREAD

**Issue by brabbitdousha** [mmp/pbrt-v4-scenes#8]
I have to admit the curly-hair.pbrt is really big...I am using RTX3060 with VS2019 on windows...still get the "CUDA error: out of memory".....  Is hair-actual-bsdf.pbrt tested on GPU?

**Comment by mmp** [comment]
I just double checked: on linux with an RTX A6000, it renders fine. It uses about 12GB of memory, which is probably why the RTX3060 can't render it. (GPU support for curves in pbrt-v4 is currently very expensive memory-wise; at some point that will be improved...)

**Comment by brabbitdousha** [comment]
ok..thank you very much..really looking forward to the new book :)
